theme: jekyll-theme-architect
title: Interacting with Computers for Art
description: This is the GitHub pages site for ICCC22 tutorial: "Methods of interacting with computational systems for live artistic performance".
