theme: jekyll-theme-architect
title: Methods of interacting with computational systems for live artistic performance
description: This is the GitHub pages site for ICCC22 tutorial 'Methods of interacting with computational systems for live artistic performance'
